# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            aerohit
tagline:          'Wander and Coder'
description:      'A coder from the land of snake charmers and elephants.'
url:              http://aerohitsaxena.com
baseurl:          /

paginate:         5
