# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /scribbles/:title
relative_permalinks: true

# Setup
title:            aerohit
tagline:          'Wander and Coder'
description:      'Coder from the land of snake charmers and cow worshippers.'
url:              http://aerohitsaxena.com
baseurl:          /

paginate:         5

github:
    repo:         https://github.com/aerohit

theme: jekyll-theme-minimal